# Generated by Django 3.1.3 on 2020-11-28 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diseasestatus',
            old_name='title',
            new_name='disease_status_title',
        ),
        migrations.RenameField(
            model_name='patientstatus',
            old_name='title',
            new_name='patient_status_title',
        ),
        migrations.RenameField(
            model_name='symptom',
            old_name='title',
            new_name='symptom_title',
        ),
    ]
