# Generated by Django 3.1.3 on 2020-11-27 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diseasestatus',
            name='is_System',
            field=models.BooleanField(default=False),
        ),
    ]
