# Generated by Django 3.1.3 on 2020-11-18 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20201117_1932'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Illness',
            new_name='PatientSymptom',
        ),
        migrations.AddField(
            model_name='status',
            name='status_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='relatedpeople',
            name='email',
            field=models.EmailField(max_length=30),
        ),
    ]
