# Generated by Django 3.1.3 on 2020-11-19 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20201118_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='symptom',
            name='weight',
            field=models.IntegerField(default=0),
        ),
    ]
