# Generated by Django 3.1.3 on 2020-11-19 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_symptom_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='status_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
