# Generated by Django 3.1.3 on 2020-11-21 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20201119_2041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='symptom',
            name='weight',
        ),
    ]
