# Generated by Django 3.1.3 on 2020-11-21 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_remove_symptom_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='symptom',
            name='weight',
            field=models.IntegerField(default=0),
        ),
    ]
